CREATE TABLE pos_system_cash_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_opening_id UUID NOT NULL,
    type VARCHAR(10) NOT NULL DEFAULT 'SALE' CHECK(type in ('INCOME', 'EXPENSE', 'SALE')),
    amount NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK(amount>=0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE pos_system_cash_movements IS
'Movimientos de caja del sistema POS';

COMMENT ON COLUMN pos_system_cash_movements.id IS
'Identificador único de movimientos de caja';

COMMENT ON COLUMN pos_system_cash_movements.cash_opening_id IS
'Relacion con apertura de caja';

COMMENT ON COLUMN pos_system_cash_movements.type IS
'Tipo de movimiento realizado, puede ser: INCOME, EXPENSE, SALE';

COMMENT ON COLUMN pos_system_cash_movements.amount IS
'Monto del movimiento realizado, debe ser positivo';

COMMENT ON COLUMN pos_system_cash_movements.created_at IS
'Fecha de creacion de la apertura de caja';
