CREATE TABLE pos_system_inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    type VARCHAR(10) NOT NULL DEFAULT 'SALE' CHECK(type in ('SALE', 'PURCHASE', 'ADJUSTMENT', 'RETURN')),
    quantity INTEGER NOT NULL DEFAULT 0 CHECK(quantity>=0),
    previous_stock INTEGER NOT NULL DEFAULT 0 CHECK(previous_stock>=0),
    new_stock INTEGER NOT NULL DEFAULT 0 CHECK(new_stock>=0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL
);

COMMENT ON TABLE pos_system_inventory_movements IS
'Movimientos de inventario del sistema POS';

COMMENT ON COLUMN pos_system_inventory_movements.id IS
'Identificador único de movimientos de inventario';

COMMENT ON COLUMN pos_system_inventory_movements.product_id IS
'Relacion con productos';

COMMENT ON COLUMN pos_system_inventory_movements.user_id IS
'Relacion con usuario activo';

COMMENT ON COLUMN pos_system_inventory_movements.type IS
'Tipo de movimiento realizado, puede ser: SALE, PURCHASE, ADJUSTMENT, RETURN';

COMMENT ON COLUMN pos_system_inventory_movements.quantity IS
'Cantidad que dependiendo del tipo pueder ser retirada, ingresada, devuelta, etc, debe ser positivo';

COMMENT ON COLUMN pos_system_inventory_movements.previous_stock IS
'Stock previo al movimiento del inventario, debe ser positivo';

COMMENT ON COLUMN pos_system_inventory_movements.new_stock IS
'Stock nuevo luego de realizado el movimiento del inventario, debe ser positivo';

COMMENT ON COLUMN pos_system_inventory_movements.created_at IS
'Fecha de creacion de la apertura de caja';

COMMENT ON COLUMN pos_system_inventory_movements.updated_at IS
'Fecha de actualizacion de la apertura de caja';