CREATE TABLE pos_system_tax_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate INTEGER NOT NULL DEFAULT 18 CHECK(rate>0),
    status VARCHAR(1) NOT NULL DEFAULT 'A' CHECK(status IN ('A','I')),
    effective_from TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    effective_to TIMESTAMPTZ DEFAULT NULL
);

COMMENT ON TABLE pos_system_tax_rates IS
'Historial de impuestos del sistema POS';

COMMENT ON COLUMN pos_system_tax_rates.id IS
'Identificador único del impuesto';

COMMENT ON COLUMN pos_system_tax_rates.rate IS
'Inpuesto aplicado, tiene que ser en entero';

COMMENT ON COLUMN pos_system_tax_rates.effective_from IS
'Fecha de aplicacion del impuesto a los productos';

COMMENT ON COLUMN pos_system_tax_rates.effective_to IS
'Fecha de caducidad del impuesto a los productos';
