CREATE TABLE pos_system_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(6) NOT NULL UNIQUE,
    description VARCHAR(16) NOT NULL UNIQUE,
    status VARCHAR(1) NOT NULL DEFAULT 'A' CHECK(status IN ('A','I')),
    soft_delete TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT NULL
);

COMMENT ON TABLE pos_system_roles IS
'Roles del sistema POS';

COMMENT ON COLUMN pos_system_roles.id IS
'Identificador único del rol';

COMMENT ON COLUMN pos_system_roles.code IS
'Codigo de rol generado aleatoreamente';

COMMENT ON COLUMN pos_system_roles.description IS
'Descripcion sera de tipo ADMIN, CAJA, LOGISTICA';

COMMENT ON COLUMN pos_system_roles.status IS
'Estado del rol: A = activo, I = inactivo';

COMMENT ON COLUMN pos_system_roles.soft_delete IS
'Fecha se elimina rol';

COMMENT ON COLUMN pos_system_roles.created_at IS
'Fecha de creacion de rol';

COMMENT ON COLUMN pos_system_roles.updated_at IS
'Fecha de actualizacion del estado del rol';