CREATE TABLE pos_system_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    description VARCHAR(200) NOT NULL,
    sale_price NUMERIC(7,2) NOT NULL DEFAULT 1 CHECK(sale_price>0),
    stock INTEGER NOT NULL DEFAULT 0 CHECK(stock>=0),
    minimum_stock INTEGER NOT NULL DEFAULT 1 CHECK(minimum_stock>0),
    sku VARCHAR(12) NOT NULL UNIQUE,
    upc TEXT NOT NULL UNIQUE,
    status CHAR(1) NOT NULL DEFAULT 'A' CHECK(status IN ('A','I')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL
);

COMMENT ON TABLE pos_system_products IS
'Productos del sistema POS';

COMMENT ON COLUMN pos_system_products.id IS
'Identificador único del producto';

COMMENT ON COLUMN pos_system_products.name IS
'Nombre del producto';

COMMENT ON COLUMN pos_system_products.description IS
'Descripcion del producto';

COMMENT ON COLUMN pos_system_products.sale_price IS
'Precio de venta del producto tiene que ser positivo';

COMMENT ON COLUMN pos_system_products.stock IS
'Cantidad de productos disponible tiene que ser positivo';

COMMENT ON COLUMN pos_system_products.minimum_stock IS
'Cantidad minima de productos tiene que ser positivo';

COMMENT ON COLUMN pos_system_products.sku IS
'Codigo unico de indentificacion del producto';

COMMENT ON COLUMN pos_system_products.upc IS
'Codigo unico de barras del producto';

COMMENT ON COLUMN pos_system_products.status IS
'Estado del producto: A = activo, I = inactivo';

COMMENT ON COLUMN pos_system_products.created_at IS
'Fecha de creacion de producto';

COMMENT ON COLUMN pos_system_products.updated_at IS
'Fecha de actualizacion de producto';