CREATE TABLE pos_system_sale_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id UUID NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0 CHECK(quantity>=0),
    unit_price NUMERIC(7,2) NOT NULL DEFAULT 1 CHECK(unit_price>0),
    subtotal NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK(subtotal>=0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE pos_system_sale_details IS
'Detalle de la venta del sistema POS';

COMMENT ON COLUMN pos_system_sale_details.id IS
'Identificador único del detalle de la venta';

COMMENT ON COLUMN pos_system_sale_details.sale_id IS
'Relacion con venta realizada';

COMMENT ON COLUMN pos_system_sale_details.product_id IS
'Relacion con producto';

COMMENT ON COLUMN pos_system_sale_details.quantity IS
'Cantidad de productos adquiridos debe ser positivo';

COMMENT ON COLUMN pos_system_sale_details.unit_price IS
'Precio de unidad de producto debe ser positivo';

COMMENT ON COLUMN pos_system_sale_details.subtotal IS
'Subtotal de la venta que se calcula quantity * unit_price';

COMMENT ON COLUMN pos_system_sale_details.created_at IS
'Fecha de creacion de la venta';
