CREATE TABLE pos_system_payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(10) NOT NULL DEFAULT 'CONTADO' CHECK(name in ('CONTADO', 'YAPE', 'PLIN', 'TARJETA')),
    status VARCHAR(1) NOT NULL DEFAULT 'A' CHECK(status IN ('A','I')),
    soft_delete TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT NULL
);

COMMENT ON TABLE pos_system_payment_methods IS
'Metodo de pago del sistema POS';

COMMENT ON COLUMN pos_system_payment_methods.name IS
'Nombre del metodo de pago, solo puede ser CONTADO, YAPE, PLIN, TARJETA';

COMMENT ON COLUMN pos_system_payment_methods.status IS
'Estado del metodo de pago: A = activo, I = inactivo';

COMMENT ON COLUMN pos_system_payment_methods.soft_delete IS
'Fecha se elimina metodo de pago';

COMMENT ON COLUMN pos_system_payment_methods.created_at IS
'Fecha de creacion del metodo de pago';

COMMENT ON COLUMN pos_system_payment_methods.updated_at IS
'Fecha de actualizacion del metodo de pago';
