CREATE TABLE pos_system_payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(10) NOT NULL DEFAULT 'EFECTIVO' CHECK(name in ('EFECTIVO', 'YAPE', 'PLIN', 'TARJETA')),
    status CHAR(1) NOT NULL DEFAULT 'A' CHECK(status IN ('A','I')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL
);

COMMENT ON TABLE pos_system_payment_methods IS
'Metodo de pago del sistema POS';

COMMENT ON COLUMN pos_system_payment_methods.name IS
'Nombre del metodo de pago, solo puede ser EFECTIVO, YAPE, PLIN, TARJETA';

COMMENT ON COLUMN pos_system_payment_methods.status IS
'Estado del metodo de pago: A = activo, I = inactivo';

COMMENT ON COLUMN pos_system_payment_methods.created_at IS
'Fecha de creacion del metodo de pago';

COMMENT ON COLUMN pos_system_payment_methods.updated_at IS
'Fecha de actualizacion del metodo de pago';
